### PR TITLE
Add logicalType/decimal support to read bytes

### PR DESCRIPTION
**Pull request by ralphschindler**
This PR adds support for (at least) reading streams topics that have a schema that includes an Avro `byte` type with `logicalType = "decimal"` to be able to decode it into a decimal (instead of returning the bytes in the resulting structure.

Outstanding questions:
- I would like to add a test, do I do that [here](https://github.com/flix-tech/avro-php/blob/master/test/IODatumReaderTest.php)?
- Do I need to add the same functionality to `write_bytes()`?

Reference for this implementation is here: https://avro.apache.org/docs/1.10.2/spec.html#Decimal

Thanks for your library and assistance!

### CODE REVIEW

**Comment by ralphschindler** [comment]
Hi @tPl0ch just pinging if there is any insight you have on this. Thanks again for maintaining this!

**Comment by stefankleff** [comment]
Thank you @ralphschindler for implementing this feature. We had the same need need, and will use your PR.
@tPl0ch It would be great if this could be merged.

**Comment by stefankleff** [comment]
@tPl0ch Thanks for merging and your overall effort! 
We've forked the project and using it with the change for more two weeks now, and we don't have any issues.

**Comment by tPl0ch** [comment]
@stefankleff @ralphschindler released as https://github.com/flix-tech/avro-php/releases/tag/5.0.1

**Comment by ralphschindler** [comment]
Apologies for being silent, I am unsure why I didn't get notifications of communications on updates to this issue. In any case, thank you for merging! I'll be glad to assist in testing future PRs, I would just need a little direction. Thanks again!

**Pull request merged**
