### PR TITLE
Php82

### PR DESCRIPTION
**Pull request by MaurizioMoreo**
This PR solves the dynamic properties errors in PHP 8.2

### CODE REVIEW

**Comment by BafS** [comment]
@tPl0ch @axelrtgs any chance we can get this merged?

**Comment by MaurizioMoreo** [comment]
@tPl0ch @axelrtgs @bajdzun @fcoedno @smalot @nick-zh @offdev @alumarcu @danez is anyone maintaining this repo?

**Comment by MaurizioMoreo** [comment]
Ok sorry for the noise, just wanted to know if anyone is taking care of it. I'll remove the previous comment.

**Comment by nick-zh** [comment]
@tPl0ch :)

**Comment by tPl0ch** [comment]
Released as version 5.0.0

https://github.com/flix-tech/avro-php/releases/tag/5.0.0

**Comment by BafS** [comment]
You're right, the last version was the v4 but I updated it (I didn't know you could force it without credentials) so now it should be good 👍

**Pull request merged**
