### PR TITLE
Add fix from Avro main stream for broken schema evolution

### PR DESCRIPTION
**Pull request by nick-zh**
all credits go to @siad007, who fixed this for apache/avro:
https://github.com/apache/avro/pull/912

### CODE REVIEW

**Comment by nick-zh** [comment]
@tPl0ch without this fix, schema evolution is currently broken when you have e.g. a new optional field of type: [null, string]

**Comment by tPl0ch** [comment]
LGTM, gonna release a new version this afternoon.

**Comment by nick-zh** [comment]
@tPl0ch awesome thx a lot!

**Comment by tPl0ch** [comment]
Released in 4.0.1:

https://github.com/flix-tech/avro-php/releases/tag/4.0.1

**Comment by nick-zh** [comment]
@tPl0ch any plans on a new release for `avro-serde-php` with `php-avro:4.x` ?

**Pull request merged**
